const CONFIG = {
    introTitle: 'Chị Hiền à!',
    introDesc: `Emm yêu chị nhiều lắm`,
    btnIntro: 'Bấm tiếp đi chị',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Yeuu emm <33',
    btnNo: 'Không, Bé :3',
    question:'Chị cóa yeuu em hong <3',
    btnReply: 'Gửi cho em <3',
    reply: 'Chị yêu em <33333333',
    mess: 'Em biết mà 🥰. Yêu chị nhiều nhiều 😘😘',
    messDesc: 'Yêu chị<3.',
    btnAccept: 'Dạaaaaa <3',
    messLink: 'https://m.facebook.com/thang.diep06'
